POST http://localhost:3030/ HTTP/1.1
Content-Type: application/json

{
    "identifier": "ZZ123",
    "altitude": 15000
}

###
POST http://localhost:3030/ HTTP/1.1
Content-Type: application/json

{
    "identifier": "AB111",
    "altitude": 10000
}

###
POST http://localhost:3030/ HTTP/1.1
Content-Type: application/json

{
    "identifier": "CC222",
    "altitude": 150
}

###
GET http://localhost:3030/database/

###
GET http://localhost:3030/database/
Content-Type: application/json

{
    "identifier": "ZZ123"
}

###
POST http://localhost:3030/raw HTTP/1.1
Content-Type: application/json

{
    "identifier": "AA000",
    "altitude": 12345
}